＃文件：.github / workflows / repo-sync.yml
名称：sync-sazs34-scripts
上：
  时间表：
    -cron：“ 5 0,7,15 * * *”
  工作流程调度：
  看：
    类型：开始
  repository_dispatch：
    类型：sync-sazs34-scripts
职位：
  回购同步：
    环境：
      PAT：$ {{secrets.PAT || github.event.client_payload.PAT}}＃此处PAT需要申请，教程详见：https：//www.jianshu.com/p/bb82b3ad1d11
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    脚步：
      -用途：actions / checkout @ v2
        与：
          持久凭证：false

      -名称：同步sazs34-scripts
        用途：repo-sync / github-sync @ v2
        如果：env.PAT
        与：
          source_repo：“ https://github.com/sazs34/MyActions.git”
          source_branch：“大师”
          destination_branch：“主要”
          github_token：$ {{secrets.PAT || github.event.client_payload.PAT}}

